### ISSUE TITLE
Alternation in bracketed groups

### ISSUE THREAD

**Issue by DivergentClouds** [crb233/unarian#10]
The spec does not make clear how this is evaluated.
```
if=0 { { - 0 | + } - }
```
I can figure out by reading the examples that the last `-` is not considered part of the alternation RHS, but the spec does not show that as far as I can tell.

**Comment by crb233** [comment]
Good catch, I think you're right. I'll add something about that

**Comment by DivergentClouds** [comment]
I found the answer hidden in the Learn By Example section, as a heads up.
