### ISSUE TITLE
Alternation on complex failure

### ISSUE THREAD

**Issue by DivergentClouds** [crb233/unarian#11]
If the function `{ - - - | + }` is called on the value `2` is the result `1` or `3`. I don't see this defined in the spec.

**Comment by crb233** [comment]
The result should be $3$ by the following rules from the spec:
1. "increment adds one to its input"
2. "decrement subtracts one from its input. However, decrement can fail if applied to input $0$"
3. "if any function in a composition fails, then the composite function as a whole also fails"
4. "Evaluating an alternation on input $x$ consists of evaluating each function from left to right on input $x$ if and only if all previous functions failed. The result of the alternation is the result of the last function to be evaluated"
5. "Evaluating an expression containing a bracketed group can be done by treating the group as a reference to a new function defined by the contents of the group"

Evaluation should look something like this, where $x \rightarrow$ `expr` means evaluating `expr` on input $x$, and $\bot$ represents a failure:

| Rule Used | Evaluation State |
|----------------|-------------------------|
| (start) | <tab> $2 \rightarrow$ <code>{ - - - &#124; + }</code> |
| rule 5 | $2 \rightarrow$ <code>- - - &#124; +</code> |
| rule 4 | $2 \rightarrow$ `- - -` **or** $2 \rightarrow$ `+` |
| rule 2 | $1 \rightarrow$ `- -` **or** $2 \rightarrow$ `+` |
| rule 2 | $0 \rightarrow$ `-` **or** $2 \rightarrow$ `+` |
| rule 2 | $\bot$ **or** $2 \rightarrow$ `+` |
| rule 4 | $2 \rightarrow$ `+` |
| rule 1 | $3$ |

**Comment by DivergentClouds** [comment]
thank you
