### ISSUE TITLE
Library behavior is undefined

### ISSUE THREAD

**Issue by DivergentClouds** [crb233/unarian#8]
[This line](https://github.com/crb233/unarian/blob/5dde93d94cf310d4ebf4b266212c7a8b2e4a192e/README.md?plain=1#L13) in README.md says 
> Otherwise it is considered a library rather than a standalone program. 

What is a Unarian library and how are they used? I don't think there is a need for Unarian to have libraries as a language feature as it adds more complexity for ultimately very little gain imo.

**Comment by crb233** [comment]
Thanks for all the feedback! The main reason I wanted libraries comes from writing `fibonacci.un` in the examples, which has a lot of tedious logic devoted to operations acting on three simulated registers. While this isn't really a practical language, it would be a little easier to use if tedious logic could be packaged into libraries so they don't have to be copy-pasted around.

To support libraries without complicating the language with import statements or something similar, the command line interface could accept a sequence of files that have no conflicting definitions and either (1) a `main` function or (2) a user-provided expression to evaluate

**Comment by DivergentClouds** [comment]
np on the feedback, glad it's appreciated. I guess my thoughts on the libraries in the lang is that can be implimentation defined as it's just a matter of how input files are handled; it doesn't relate to the language logic.

**Comment by crb233** [comment]
Good point, I like this way of thinking about it
